/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrgSlugRouteImport } from './routes/$orgSlug'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SelectRouteImport } from './routes/select'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OrgSlugIndexRouteImport } from './routes/$orgSlug/index'
import { Route as OrgSlugAgentsRouteImport } from './routes/$orgSlug/agents'
import { Route as OrgSlugApiKeysRouteImport } from './routes/$orgSlug/api-keys'
import { Route as OrgSlugAuditLogsRouteImport } from './routes/$orgSlug/audit-logs'
import { Route as OrgSlugBillingRouteImport } from './routes/$orgSlug/billing'
import { Route as OrgSlugDomainsRouteImport } from './routes/$orgSlug/domains'
import { Route as OrgSlugMembersRouteImport } from './routes/$orgSlug/members'
import { Route as OrgSlugRequestsRouteImport } from './routes/$orgSlug/requests'
import { Route as OrgSlugUsageRouteImport } from './routes/$orgSlug/usage'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as MarketingChangelogRouteImport } from './routes/_marketing/changelog'
import { Route as MarketingContactRouteImport } from './routes/_marketing/contact'
import { Route as MarketingPluginsRouteImport } from './routes/_marketing/plugins'
import { Route as MarketingPricingRouteImport } from './routes/_marketing/pricing'
import { Route as MarketingPrivacyRouteImport } from './routes/_marketing/privacy'
import { Route as MarketingReportBugRouteImport } from './routes/_marketing/report-bug'
import { Route as MarketingTermsRouteImport } from './routes/_marketing/terms'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminActionsRouteImport } from './routes/admin/actions'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'
import { Route as AdminChartsRouteImport } from './routes/admin/charts'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin/subscriptions'
import { Route as AdminTunnelsRouteImport } from './routes/admin/tunnels'
import { Route as AdminUsageRouteImport } from './routes/admin/usage'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as CliLoginRouteImport } from './routes/cli/login'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as OrgSlugSettingsIndexRouteImport } from './routes/$orgSlug/settings/index'
import { Route as OrgSlugSettingsOrganizationRouteImport } from './routes/$orgSlug/settings/organization'
import { Route as OrgSlugSettingsProfileRouteImport } from './routes/$orgSlug/settings/profile'
import { Route as OrgSlugTunnelsIndexRouteImport } from './routes/$orgSlug/tunnels/index'
import { Route as OrgSlugTunnelsTunnelIdRouteImport } from './routes/$orgSlug/tunnels/$tunnelId'
import { Route as MarketingPluginsIndexRouteImport } from './routes/_marketing/plugins/index'
import { Route as MarketingPluginsPluginIdRouteImport } from './routes/_marketing/plugins/$pluginId'
import { Route as AdminOrganizationsIndexRouteImport } from './routes/admin/organizations/index'
import { Route as AdminOrganizationsOrganizationIDRouteImport } from './routes/admin/organizations/$organizationID'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'

const OrgSlugRoute = OrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoute = SelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugAgentsRoute = OrgSlugAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugApiKeysRoute = OrgSlugApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugAuditLogsRoute = OrgSlugAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugBillingRoute = OrgSlugBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugDomainsRoute = OrgSlugDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugMembersRoute = OrgSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugRequestsRoute = OrgSlugRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugUsageRoute = OrgSlugUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => OrgSlugRoute,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingChangelogRoute = MarketingChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPluginsRoute = MarketingPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPricingRoute = MarketingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPrivacyRoute = MarketingPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingReportBugRoute = MarketingReportBugRouteImport.update({
  id: '/report-bug',
  path: '/report-bug',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingTermsRoute = MarketingTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => MarketingRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActionsRoute = AdminActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChartsRoute = AdminChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTunnelsRoute = AdminTunnelsRouteImport.update({
  id: '/tunnels',
  path: '/tunnels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsageRoute = AdminUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AdminRoute,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CliLoginRoute = CliLoginRouteImport.update({
  id: '/cli/login',
  path: '/cli/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugSettingsIndexRoute = OrgSlugSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugSettingsOrganizationRoute =
  OrgSlugSettingsOrganizationRouteImport.update({
    id: '/settings/organization',
    path: '/settings/organization',
    getParentRoute: () => OrgSlugRoute,
  } as any)
const OrgSlugSettingsProfileRoute = OrgSlugSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugTunnelsIndexRoute = OrgSlugTunnelsIndexRouteImport.update({
  id: '/tunnels/',
  path: '/tunnels/',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugTunnelsTunnelIdRoute = OrgSlugTunnelsTunnelIdRouteImport.update({
  id: '/tunnels/$tunnelId',
  path: '/tunnels/$tunnelId',
  getParentRoute: () => OrgSlugRoute,
} as any)
const MarketingPluginsIndexRoute = MarketingPluginsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingPluginsRoute,
} as any)
const MarketingPluginsPluginIdRoute =
  MarketingPluginsPluginIdRouteImport.update({
    id: '/$pluginId',
    path: '/$pluginId',
    getParentRoute: () => MarketingPluginsRoute,
  } as any)
const AdminOrganizationsIndexRoute = AdminOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsOrganizationIDRoute =
  AdminOrganizationsOrganizationIDRouteImport.update({
    id: '/organizations/$organizationID',
    path: '/organizations/$organizationID',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$orgSlug': typeof OrgSlugRouteWithChildren
  '/': typeof MarketingIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/select': typeof SelectRoute
  '/signup': typeof SignupRoute
  '/$orgSlug/agents': typeof OrgSlugAgentsRoute
  '/$orgSlug/api-keys': typeof OrgSlugApiKeysRoute
  '/$orgSlug/audit-logs': typeof OrgSlugAuditLogsRoute
  '/$orgSlug/billing': typeof OrgSlugBillingRoute
  '/$orgSlug/domains': typeof OrgSlugDomainsRoute
  '/$orgSlug/members': typeof OrgSlugMembersRoute
  '/$orgSlug/requests': typeof OrgSlugRequestsRoute
  '/$orgSlug/usage': typeof OrgSlugUsageRoute
  '/changelog': typeof MarketingChangelogRoute
  '/contact': typeof MarketingContactRoute
  '/plugins': typeof MarketingPluginsRouteWithChildren
  '/pricing': typeof MarketingPricingRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/report-bug': typeof MarketingReportBugRoute
  '/terms': typeof MarketingTermsRoute
  '/admin/actions': typeof AdminActionsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/charts': typeof AdminChartsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/tunnels': typeof AdminTunnelsRoute
  '/admin/usage': typeof AdminUsageRoute
  '/api/search': typeof ApiSearchRoute
  '/cli/login': typeof CliLoginRoute
  '/docs/$': typeof DocsSplatRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$orgSlug/settings/organization': typeof OrgSlugSettingsOrganizationRoute
  '/$orgSlug/settings/profile': typeof OrgSlugSettingsProfileRoute
  '/$orgSlug/tunnels/$tunnelId': typeof OrgSlugTunnelsTunnelIdRoute
  '/plugins/$pluginId': typeof MarketingPluginsPluginIdRoute
  '/admin/organizations/$organizationID': typeof AdminOrganizationsOrganizationIDRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/$orgSlug/settings/': typeof OrgSlugSettingsIndexRoute
  '/$orgSlug/tunnels/': typeof OrgSlugTunnelsIndexRoute
  '/plugins/': typeof MarketingPluginsIndexRoute
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/select': typeof SelectRoute
  '/signup': typeof SignupRoute
  '/$orgSlug/agents': typeof OrgSlugAgentsRoute
  '/$orgSlug/api-keys': typeof OrgSlugApiKeysRoute
  '/$orgSlug/audit-logs': typeof OrgSlugAuditLogsRoute
  '/$orgSlug/billing': typeof OrgSlugBillingRoute
  '/$orgSlug/domains': typeof OrgSlugDomainsRoute
  '/$orgSlug/members': typeof OrgSlugMembersRoute
  '/$orgSlug/requests': typeof OrgSlugRequestsRoute
  '/$orgSlug/usage': typeof OrgSlugUsageRoute
  '/changelog': typeof MarketingChangelogRoute
  '/contact': typeof MarketingContactRoute
  '/pricing': typeof MarketingPricingRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/report-bug': typeof MarketingReportBugRoute
  '/terms': typeof MarketingTermsRoute
  '/admin/actions': typeof AdminActionsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/charts': typeof AdminChartsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/tunnels': typeof AdminTunnelsRoute
  '/admin/usage': typeof AdminUsageRoute
  '/api/search': typeof ApiSearchRoute
  '/cli/login': typeof CliLoginRoute
  '/docs/$': typeof DocsSplatRoute
  '/$orgSlug': typeof OrgSlugIndexRoute
  '/': typeof MarketingIndexRoute
  '/admin': typeof AdminIndexRoute
  '/$orgSlug/settings/organization': typeof OrgSlugSettingsOrganizationRoute
  '/$orgSlug/settings/profile': typeof OrgSlugSettingsProfileRoute
  '/$orgSlug/tunnels/$tunnelId': typeof OrgSlugTunnelsTunnelIdRoute
  '/plugins/$pluginId': typeof MarketingPluginsPluginIdRoute
  '/admin/organizations/$organizationID': typeof AdminOrganizationsOrganizationIDRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/$orgSlug/settings': typeof OrgSlugSettingsIndexRoute
  '/$orgSlug/tunnels': typeof OrgSlugTunnelsIndexRoute
  '/plugins': typeof MarketingPluginsIndexRoute
  '/admin/organizations': typeof AdminOrganizationsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$orgSlug': typeof OrgSlugRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/select': typeof SelectRoute
  '/signup': typeof SignupRoute
  '/$orgSlug/agents': typeof OrgSlugAgentsRoute
  '/$orgSlug/api-keys': typeof OrgSlugApiKeysRoute
  '/$orgSlug/audit-logs': typeof OrgSlugAuditLogsRoute
  '/$orgSlug/billing': typeof OrgSlugBillingRoute
  '/$orgSlug/domains': typeof OrgSlugDomainsRoute
  '/$orgSlug/members': typeof OrgSlugMembersRoute
  '/$orgSlug/requests': typeof OrgSlugRequestsRoute
  '/$orgSlug/usage': typeof OrgSlugUsageRoute
  '/_marketing/changelog': typeof MarketingChangelogRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/_marketing/plugins': typeof MarketingPluginsRouteWithChildren
  '/_marketing/pricing': typeof MarketingPricingRoute
  '/_marketing/privacy': typeof MarketingPrivacyRoute
  '/_marketing/report-bug': typeof MarketingReportBugRoute
  '/_marketing/terms': typeof MarketingTermsRoute
  '/admin/actions': typeof AdminActionsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/charts': typeof AdminChartsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/tunnels': typeof AdminTunnelsRoute
  '/admin/usage': typeof AdminUsageRoute
  '/api/search': typeof ApiSearchRoute
  '/cli/login': typeof CliLoginRoute
  '/docs/$': typeof DocsSplatRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$orgSlug/settings/organization': typeof OrgSlugSettingsOrganizationRoute
  '/$orgSlug/settings/profile': typeof OrgSlugSettingsProfileRoute
  '/$orgSlug/tunnels/$tunnelId': typeof OrgSlugTunnelsTunnelIdRoute
  '/_marketing/plugins/$pluginId': typeof MarketingPluginsPluginIdRoute
  '/admin/organizations/$organizationID': typeof AdminOrganizationsOrganizationIDRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/$orgSlug/settings/': typeof OrgSlugSettingsIndexRoute
  '/$orgSlug/tunnels/': typeof OrgSlugTunnelsIndexRoute
  '/_marketing/plugins/': typeof MarketingPluginsIndexRoute
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$orgSlug'
    | '/'
    | '/admin'
    | '/login'
    | '/select'
    | '/signup'
    | '/$orgSlug/agents'
    | '/$orgSlug/api-keys'
    | '/$orgSlug/audit-logs'
    | '/$orgSlug/billing'
    | '/$orgSlug/domains'
    | '/$orgSlug/members'
    | '/$orgSlug/requests'
    | '/$orgSlug/usage'
    | '/changelog'
    | '/contact'
    | '/plugins'
    | '/pricing'
    | '/privacy'
    | '/report-bug'
    | '/terms'
    | '/admin/actions'
    | '/admin/audit-logs'
    | '/admin/charts'
    | '/admin/subscriptions'
    | '/admin/tunnels'
    | '/admin/usage'
    | '/api/search'
    | '/cli/login'
    | '/docs/$'
    | '/$orgSlug/'
    | '/admin/'
    | '/$orgSlug/settings/organization'
    | '/$orgSlug/settings/profile'
    | '/$orgSlug/tunnels/$tunnelId'
    | '/plugins/$pluginId'
    | '/admin/organizations/$organizationID'
    | '/admin/users/$userId'
    | '/$orgSlug/settings/'
    | '/$orgSlug/tunnels/'
    | '/plugins/'
    | '/admin/organizations/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/select'
    | '/signup'
    | '/$orgSlug/agents'
    | '/$orgSlug/api-keys'
    | '/$orgSlug/audit-logs'
    | '/$orgSlug/billing'
    | '/$orgSlug/domains'
    | '/$orgSlug/members'
    | '/$orgSlug/requests'
    | '/$orgSlug/usage'
    | '/changelog'
    | '/contact'
    | '/pricing'
    | '/privacy'
    | '/report-bug'
    | '/terms'
    | '/admin/actions'
    | '/admin/audit-logs'
    | '/admin/charts'
    | '/admin/subscriptions'
    | '/admin/tunnels'
    | '/admin/usage'
    | '/api/search'
    | '/cli/login'
    | '/docs/$'
    | '/$orgSlug'
    | '/'
    | '/admin'
    | '/$orgSlug/settings/organization'
    | '/$orgSlug/settings/profile'
    | '/$orgSlug/tunnels/$tunnelId'
    | '/plugins/$pluginId'
    | '/admin/organizations/$organizationID'
    | '/admin/users/$userId'
    | '/$orgSlug/settings'
    | '/$orgSlug/tunnels'
    | '/plugins'
    | '/admin/organizations'
    | '/admin/users'
  id:
    | '__root__'
    | '/$orgSlug'
    | '/_marketing'
    | '/admin'
    | '/login'
    | '/select'
    | '/signup'
    | '/$orgSlug/agents'
    | '/$orgSlug/api-keys'
    | '/$orgSlug/audit-logs'
    | '/$orgSlug/billing'
    | '/$orgSlug/domains'
    | '/$orgSlug/members'
    | '/$orgSlug/requests'
    | '/$orgSlug/usage'
    | '/_marketing/changelog'
    | '/_marketing/contact'
    | '/_marketing/plugins'
    | '/_marketing/pricing'
    | '/_marketing/privacy'
    | '/_marketing/report-bug'
    | '/_marketing/terms'
    | '/admin/actions'
    | '/admin/audit-logs'
    | '/admin/charts'
    | '/admin/subscriptions'
    | '/admin/tunnels'
    | '/admin/usage'
    | '/api/search'
    | '/cli/login'
    | '/docs/$'
    | '/$orgSlug/'
    | '/_marketing/'
    | '/admin/'
    | '/$orgSlug/settings/organization'
    | '/$orgSlug/settings/profile'
    | '/$orgSlug/tunnels/$tunnelId'
    | '/_marketing/plugins/$pluginId'
    | '/admin/organizations/$organizationID'
    | '/admin/users/$userId'
    | '/$orgSlug/settings/'
    | '/$orgSlug/tunnels/'
    | '/_marketing/plugins/'
    | '/admin/organizations/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  OrgSlugRoute: typeof OrgSlugRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SelectRoute: typeof SelectRoute
  SignupRoute: typeof SignupRoute
  ApiSearchRoute: typeof ApiSearchRoute
  CliLoginRoute: typeof CliLoginRoute
  DocsSplatRoute: typeof DocsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$orgSlug': {
      id: '/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof OrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select': {
      id: '/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof SelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/': {
      id: '/$orgSlug/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/agents': {
      id: '/$orgSlug/agents'
      path: '/agents'
      fullPath: '/$orgSlug/agents'
      preLoaderRoute: typeof OrgSlugAgentsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/api-keys': {
      id: '/$orgSlug/api-keys'
      path: '/api-keys'
      fullPath: '/$orgSlug/api-keys'
      preLoaderRoute: typeof OrgSlugApiKeysRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/audit-logs': {
      id: '/$orgSlug/audit-logs'
      path: '/audit-logs'
      fullPath: '/$orgSlug/audit-logs'
      preLoaderRoute: typeof OrgSlugAuditLogsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/billing': {
      id: '/$orgSlug/billing'
      path: '/billing'
      fullPath: '/$orgSlug/billing'
      preLoaderRoute: typeof OrgSlugBillingRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/domains': {
      id: '/$orgSlug/domains'
      path: '/domains'
      fullPath: '/$orgSlug/domains'
      preLoaderRoute: typeof OrgSlugDomainsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/members': {
      id: '/$orgSlug/members'
      path: '/members'
      fullPath: '/$orgSlug/members'
      preLoaderRoute: typeof OrgSlugMembersRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/requests': {
      id: '/$orgSlug/requests'
      path: '/requests'
      fullPath: '/$orgSlug/requests'
      preLoaderRoute: typeof OrgSlugRequestsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/usage': {
      id: '/$orgSlug/usage'
      path: '/usage'
      fullPath: '/$orgSlug/usage'
      preLoaderRoute: typeof OrgSlugUsageRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/changelog': {
      id: '/_marketing/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof MarketingChangelogRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/plugins': {
      id: '/_marketing/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof MarketingPluginsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/pricing': {
      id: '/_marketing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof MarketingPricingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/privacy': {
      id: '/_marketing/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MarketingPrivacyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/report-bug': {
      id: '/_marketing/report-bug'
      path: '/report-bug'
      fullPath: '/report-bug'
      preLoaderRoute: typeof MarketingReportBugRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/terms': {
      id: '/_marketing/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof MarketingTermsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/actions': {
      id: '/admin/actions'
      path: '/actions'
      fullPath: '/admin/actions'
      preLoaderRoute: typeof AdminActionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/charts': {
      id: '/admin/charts'
      path: '/charts'
      fullPath: '/admin/charts'
      preLoaderRoute: typeof AdminChartsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tunnels': {
      id: '/admin/tunnels'
      path: '/tunnels'
      fullPath: '/admin/tunnels'
      preLoaderRoute: typeof AdminTunnelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usage': {
      id: '/admin/usage'
      path: '/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AdminUsageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/login': {
      id: '/cli/login'
      path: '/cli/login'
      fullPath: '/cli/login'
      preLoaderRoute: typeof CliLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/settings/': {
      id: '/$orgSlug/settings/'
      path: '/settings'
      fullPath: '/$orgSlug/settings/'
      preLoaderRoute: typeof OrgSlugSettingsIndexRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/settings/organization': {
      id: '/$orgSlug/settings/organization'
      path: '/settings/organization'
      fullPath: '/$orgSlug/settings/organization'
      preLoaderRoute: typeof OrgSlugSettingsOrganizationRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/settings/profile': {
      id: '/$orgSlug/settings/profile'
      path: '/settings/profile'
      fullPath: '/$orgSlug/settings/profile'
      preLoaderRoute: typeof OrgSlugSettingsProfileRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/tunnels/': {
      id: '/$orgSlug/tunnels/'
      path: '/tunnels'
      fullPath: '/$orgSlug/tunnels/'
      preLoaderRoute: typeof OrgSlugTunnelsIndexRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/tunnels/$tunnelId': {
      id: '/$orgSlug/tunnels/$tunnelId'
      path: '/tunnels/$tunnelId'
      fullPath: '/$orgSlug/tunnels/$tunnelId'
      preLoaderRoute: typeof OrgSlugTunnelsTunnelIdRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/_marketing/plugins/': {
      id: '/_marketing/plugins/'
      path: '/'
      fullPath: '/plugins/'
      preLoaderRoute: typeof MarketingPluginsIndexRouteImport
      parentRoute: typeof MarketingPluginsRoute
    }
    '/_marketing/plugins/$pluginId': {
      id: '/_marketing/plugins/$pluginId'
      path: '/$pluginId'
      fullPath: '/plugins/$pluginId'
      preLoaderRoute: typeof MarketingPluginsPluginIdRouteImport
      parentRoute: typeof MarketingPluginsRoute
    }
    '/admin/organizations/': {
      id: '/admin/organizations/'
      path: '/organizations'
      fullPath: '/admin/organizations/'
      preLoaderRoute: typeof AdminOrganizationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations/$organizationID': {
      id: '/admin/organizations/$organizationID'
      path: '/organizations/$organizationID'
      fullPath: '/admin/organizations/$organizationID'
      preLoaderRoute: typeof AdminOrganizationsOrganizationIDRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface OrgSlugRouteChildren {
  OrgSlugAgentsRoute: typeof OrgSlugAgentsRoute
  OrgSlugApiKeysRoute: typeof OrgSlugApiKeysRoute
  OrgSlugAuditLogsRoute: typeof OrgSlugAuditLogsRoute
  OrgSlugBillingRoute: typeof OrgSlugBillingRoute
  OrgSlugDomainsRoute: typeof OrgSlugDomainsRoute
  OrgSlugMembersRoute: typeof OrgSlugMembersRoute
  OrgSlugRequestsRoute: typeof OrgSlugRequestsRoute
  OrgSlugUsageRoute: typeof OrgSlugUsageRoute
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
  OrgSlugSettingsOrganizationRoute: typeof OrgSlugSettingsOrganizationRoute
  OrgSlugSettingsProfileRoute: typeof OrgSlugSettingsProfileRoute
  OrgSlugTunnelsTunnelIdRoute: typeof OrgSlugTunnelsTunnelIdRoute
  OrgSlugSettingsIndexRoute: typeof OrgSlugSettingsIndexRoute
  OrgSlugTunnelsIndexRoute: typeof OrgSlugTunnelsIndexRoute
}

const OrgSlugRouteChildren: OrgSlugRouteChildren = {
  OrgSlugAgentsRoute: OrgSlugAgentsRoute,
  OrgSlugApiKeysRoute: OrgSlugApiKeysRoute,
  OrgSlugAuditLogsRoute: OrgSlugAuditLogsRoute,
  OrgSlugBillingRoute: OrgSlugBillingRoute,
  OrgSlugDomainsRoute: OrgSlugDomainsRoute,
  OrgSlugMembersRoute: OrgSlugMembersRoute,
  OrgSlugRequestsRoute: OrgSlugRequestsRoute,
  OrgSlugUsageRoute: OrgSlugUsageRoute,
  OrgSlugIndexRoute: OrgSlugIndexRoute,
  OrgSlugSettingsOrganizationRoute: OrgSlugSettingsOrganizationRoute,
  OrgSlugSettingsProfileRoute: OrgSlugSettingsProfileRoute,
  OrgSlugTunnelsTunnelIdRoute: OrgSlugTunnelsTunnelIdRoute,
  OrgSlugSettingsIndexRoute: OrgSlugSettingsIndexRoute,
  OrgSlugTunnelsIndexRoute: OrgSlugTunnelsIndexRoute,
}

const OrgSlugRouteWithChildren =
  OrgSlugRoute._addFileChildren(OrgSlugRouteChildren)

interface MarketingPluginsRouteChildren {
  MarketingPluginsPluginIdRoute: typeof MarketingPluginsPluginIdRoute
  MarketingPluginsIndexRoute: typeof MarketingPluginsIndexRoute
}

const MarketingPluginsRouteChildren: MarketingPluginsRouteChildren = {
  MarketingPluginsPluginIdRoute: MarketingPluginsPluginIdRoute,
  MarketingPluginsIndexRoute: MarketingPluginsIndexRoute,
}

const MarketingPluginsRouteWithChildren =
  MarketingPluginsRoute._addFileChildren(MarketingPluginsRouteChildren)

interface MarketingRouteChildren {
  MarketingChangelogRoute: typeof MarketingChangelogRoute
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingPluginsRoute: typeof MarketingPluginsRouteWithChildren
  MarketingPricingRoute: typeof MarketingPricingRoute
  MarketingPrivacyRoute: typeof MarketingPrivacyRoute
  MarketingReportBugRoute: typeof MarketingReportBugRoute
  MarketingTermsRoute: typeof MarketingTermsRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingChangelogRoute: MarketingChangelogRoute,
  MarketingContactRoute: MarketingContactRoute,
  MarketingPluginsRoute: MarketingPluginsRouteWithChildren,
  MarketingPricingRoute: MarketingPricingRoute,
  MarketingPrivacyRoute: MarketingPrivacyRoute,
  MarketingReportBugRoute: MarketingReportBugRoute,
  MarketingTermsRoute: MarketingTermsRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface AdminRouteChildren {
  AdminActionsRoute: typeof AdminActionsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminChartsRoute: typeof AdminChartsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminTunnelsRoute: typeof AdminTunnelsRoute
  AdminUsageRoute: typeof AdminUsageRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrganizationsOrganizationIDRoute: typeof AdminOrganizationsOrganizationIDRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminOrganizationsIndexRoute: typeof AdminOrganizationsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActionsRoute: AdminActionsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminChartsRoute: AdminChartsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminTunnelsRoute: AdminTunnelsRoute,
  AdminUsageRoute: AdminUsageRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOrganizationsOrganizationIDRoute: AdminOrganizationsOrganizationIDRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminOrganizationsIndexRoute: AdminOrganizationsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  OrgSlugRoute: OrgSlugRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SelectRoute: SelectRoute,
  SignupRoute: SignupRoute,
  ApiSearchRoute: ApiSearchRoute,
  CliLoginRoute: CliLoginRoute,
  DocsSplatRoute: DocsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
