root = "."
tmp_dir = "tmp/air-tunnel"

[build]
  cmd = "go build -o ./tmp/air-tunnel/outpipe-server ./cmd/tunnel"
  bin = "./tmp/air-tunnel/outpipe-server"
  full_bin = ""
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["apps", "docs", "data", "tmp", "node_modules", "target", "dist", "packages", "bin", ".air"]
  exclude_file = []
  delay = 1000
  stop_on_error = true
  log = "build-errors-tunnel.log"

[log]
  time = false

[color]
  main = "cyan"
  watcher = "blue"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
